// Server entrypoint used by the container CMD (apps/server/Dockerfile).
//
// It parses configuration from the process environment, opens the durable
// SQLite database under HAVEMIND_DATA_DIR, wires the auth/onboarding/sync
// repositories into `buildApp` (exactly as the integration harness does) and
// starts listening. Passing `auth` is what makes the invitation, owner-pairing,
// approval, bootstrap and sync routes exist — without it the process only
// serves discovery/health, which is why `/owner/pair` returned 404 in prod.

import { join } from 'node:path';

import { buildApp } from './app.js';
import { parseServerConfig, type ServerEnvironment } from './config.js';
import { openDatabase } from './db.js';
import { runMigrations } from './migrations.js';
import { BlobStore } from './blob-store.js';
import { RevisionRepository } from './revision-repository.js';
import { InvitationService } from './auth/invitations.js';
import { SessionRepository } from './auth/session-repository.js';

// The setup CLI (`havemind setup`) writes the database under this name, so the
// server must open the same file it initialised. Blobs live beside it.
const DB_FILENAME = 'havemind.db';
const BLOBS_DIRNAME = 'blobs';

function resolveDataDir(environment: ServerEnvironment): string {
  const dataDir = environment.HAVEMIND_DATA_DIR;
  if (dataDir === undefined || dataDir.trim() === '') {
    throw new Error(
      'HAVEMIND_DATA_DIR must point at the server data directory.',
    );
  }
  return dataDir;
}

async function main(): Promise<void> {
  const config = parseServerConfig(process.env);
  const dataDir = resolveDataDir(process.env);

  // Plain WAL SQLite (better-sqlite3): the database key generated by
  // `havemind generate-db-key` guards the file at rest via filesystem/secret
  // handling; the current open path applies no in-process cipher, so the server
  // opens the file exactly as the setup CLI created it.
  const database = openDatabase(join(dataDir, DB_FILENAME));
  runMigrations(database);

  const sessions = new SessionRepository(database);
  const invitations = new InvitationService(database);
  const blobStore = new BlobStore(join(dataDir, BLOBS_DIRNAME));
  const revisions = new RevisionRepository(database, blobStore);

  const app = buildApp({
    config,
    auth: {
      database,
      sessions,
      invitations,
      sync: { blobStore, database, revisions },
    },
  });

  let closing = false;
  const close = (): void => {
    if (closing) {
      return;
    }
    closing = true;
    void app.close().finally(() => {
      try {
        database.close();
      } catch {
        // The database may already be closed during shutdown; ignore.
      }
      process.exit(0);
    });
  };
  process.on('SIGTERM', close);
  process.on('SIGINT', close);

  await app.listen({ host: config.host, port: config.port });
}

main().catch((error: unknown) => {
  process.stderr.write(
    `Failed to start Havemind server: ${
      error instanceof Error ? error.message : String(error)
    }\n`,
  );
  process.exit(1);
});
